---
title: "Three Aphid Species - FP - Root biomass"
author: "Kris"
date: "`r Sys.Date()`"
output: 
  html_document: 
      toc: true
      toc_float:
        collapsed: false
        smooth_scroll: true
---
  
# Description

   
# Start
### Import pre-made functions
```{r, warning = FALSE, message = FALSE}
source("C:/Users/kreek001/OneDrive - Wageningen University & Research/R_Scripts/DHARMa_functions.R")
```
  
### Libraries
```{r, warning = FALSE, message = FALSE}
R.version$version.string # prints R version

library(car) #for Anova function
packageVersion("car")
library(emmeans) #for post hoc emmeans
packageVersion("emmeans")
library(multcomp) #for cld function at post hoc analysis
packageVersion("multcomp")
library(multcompView) #for cld function at post hoc analysis
packageVersion("multcompView")
library(ggplot2) #graphs
packageVersion("ggplot2")
library(plyr) #for summary table
packageVersion("plyr")
library(ggh4x) #for coloring strip facet wrap
packageVersion("ggh4x")
library(glmmTMB) #for doing glm with many different options
packageVersion("glmmTMB")
library(DHARMa) #for model assumptions
packageVersion("DHARMa")
```
  
## Loading data and processing
### Loading data  
```{r}
data <- read.csv("C:/Users/kreek001/OneDrive - Wageningen University & Research/Chapters/Experimental Chapter 1/Data/FP_Aphids_Root_Shoot_Biomass.csv")
```
  
### Removing NAs and sterile treatment 
```{r}
data <- data[complete.cases(data$Root_biomass), ]
data <- data[data$Aphid_species != "Bb", ]
```
  
### Defining factors  
```{r}
data$Soil_conditioning <- factor(data$Soil_conditioning, levels = c("CTRL", "Aphid"))
data$Aphid_species <- as.factor(data$Aphid_species)
```
  
# Exploring data
```{r}
str(data)
head(data, 12)
summary(data) #check for outliers
table(data$Block_g, data$Aphid_species, data$Soil_conditioning)
```

## Summary table
### Aphid_species
```{r}
DataSum <- ddply(data, c("Aphid_species", "Soil_conditioning"), summarize,
            N = sum(!is.na(Root_biomass)), #number of samples
            Mis = sum(is.na(Root_biomass)), #number of missing values
            Mean = round(mean(Root_biomass, na.rm=T),3), #mean
            Median = round(median(Root_biomass, na.rm=T),3), #median
            SD = round(sd(Root_biomass, na.rm=T),3), #standard deviation
            SE = round(sd(Root_biomass, na.rm=T) / sqrt(N),5), #standard error
            LCI = round(Mean - (2*SE),3), #lower confidence interval
            HCI = round(Mean + (2*SE),3)) # upper confidence interval
print(DataSum)
```

## Plot 
```{r, fig.width=8, fig.height=4}
ggplot(data = data,
       mapping = aes(y = Root_biomass, x = Soil_conditioning, fill = Soil_conditioning)) + #Defines the data
  stat_boxplot(aes(y = Root_biomass, x = Soil_conditioning), #Shows the error bars (should be added before box plots to have bars behind box plots)
               geom = "errorbar",
               linetype = 1,
               width = 0.2) +
  facet_wrap(~ Aphid_species,
             nrow = 1,
             #labeller = labeller(CaterpillarNr = c("4" = "4 Cat", "8" = "8 Cat"))
             ) + # Split data into three graphs, a graph for each caterpillar number
  geom_boxplot(outliers = FALSE) + #Defines that the graph will be a box plot and do not show outliers, this is shown by jitter
  geom_jitter(width = 0.25,
              height = 0,
              color = "black",
              alpha = 0.2) + # Transparency is regulated with the alpha argument
  stat_summary(fun = mean,
               geom = "point",
               size = 1.5,
               color = "white",
               shape = 18) + #Shows the mean as a white circle
  scale_y_continuous(expand = c(0, 0),        #start graph at y = min and x = min
                     #breaks = seq(0, 1, 0.25), #steps on the y-axis
                     limits = c(0, max(data$Root_biomass*1.1))) +   #y limits
  scale_fill_manual(values = c("#56B4E9", "#009E73")) + # Manually change the colors of the bars. You need to define fill in second line of the plot script to get it working; c("#009E73", "#56B4E9")
  ylab("Root biomass (g)") +    #y-label with Mp in italic
  xlab("Soil treatment") +
  theme(panel.background = element_rect(fill = "white"), #theme of the graph
        panel.border = element_blank(), #no border around the graph (for border, use: element_rect(color = "gray30", fill = NA))
        axis.line = element_line(), #show line for x and y axis
        plot.title = element_text(size = 9, hjust = 0),
        axis.text = element_text(size = 13, color = "black"),
        axis.title = element_text(size = 16),
        axis.title.x = element_text(vjust = -0.5),
        axis.title.y = element_text(vjust = 2.5), #, hjust = -0
        strip.text = element_text(size = 13),
        legend.position = "none")
```


# Statistical analysis
## All four aphid species
### Model
```{r}
lm1 <- glmmTMB(data = data, formula = Root_biomass ~ Soil_conditioning*Aphid_species, family = gaussian(link = "identity"))
lm2 <- glmmTMB(data = data, formula = Root_biomass ~ Soil_conditioning*Aphid_species + (1|Block_g), family = gaussian(link = "identity"))
lm3 <- glmmTMB(data = data, formula = log(Root_biomass) ~ Soil_conditioning*Aphid_species, family = gaussian(link = "identity"))
lm4 <- glmmTMB(data = data, formula = log(Root_biomass) ~ Soil_conditioning*Aphid_species + (1|Block_g), family = gaussian(link = "identity"))
lm5 <- glmmTMB(data = data, formula = sqrt(Root_biomass) ~ Soil_conditioning*Aphid_species, family = gaussian(link = "identity"))
lm6 <- glmmTMB(data = data, formula = sqrt(Root_biomass) ~ Soil_conditioning*Aphid_species + (1|Block_g), family = gaussian(link = "identity"))

glm1 <- glmmTMB(data = data, formula = Root_biomass ~ Soil_conditioning*Aphid_species, family = Gamma(link = "log"))
glm2 <- glmmTMB(data = data, formula = Root_biomass ~ Soil_conditioning*Aphid_species + (1|Block_g), family = Gamma(link = "log"))
glm3 <- glmmTMB(data = data, formula = log(Root_biomass + 1) ~ Soil_conditioning*Aphid_species, family = Gamma(link = "log"))
glm4 <- glmmTMB(data = data, formula = log(Root_biomass + 1) ~ Soil_conditioning*Aphid_species + (1|Block_g), family = Gamma(link = "log"))
glm5 <- glmmTMB(data = data, formula = sqrt(Root_biomass) ~ Soil_conditioning*Aphid_species, family = Gamma(link = "log"))
glm6 <- glmmTMB(data = data, formula = sqrt(Root_biomass) ~ Soil_conditioning*Aphid_species + (1|Block_g), family = Gamma(link = "log"))
```

### Model assumptions
```{r, fig.width=10, fig.height=7}
DHARMa.sum(Model = lm1)
DHARMa.sum(Model = lm2)
DHARMa.sum(Model = lm3)
DHARMa.sum(Model = lm4)
DHARMa.sum(Model = lm5)
DHARMa.sum(Model = lm6)

DHARMa.sum(Model = glm1)
DHARMa.sum(Model = glm2)
DHARMa.sum(Model = glm3)
DHARMa.sum(Model = glm4)
DHARMa.sum(Model = glm5)
DHARMa.sum(Model = glm6)
```

### Model output
```{r}
summary(glm2)
an_mod <- Anova(glm2)
an_mod 

Stats_FP_Aphid_RootBiomass <- as.data.frame(an_mod)
write.csv(Stats_FP_Aphid_RootBiomass, "C:/Users/kreek001/OneDrive - Wageningen University & Research/Chapters/Experimental Chapter 1/R_Scripts/Statistical output/Stats_FP_Aphid_RootBiomass.csv")
```

### Post hoc test
```{r}
# EMMA2 <- emmeans(lm6, pairwise ~ Soil_conditioning*Aphid_species, adjust = "tukey", type = "response") # more stringed
# EMA <- cld(EMMA2, Letters = letters)
# EMA
```


# Final figure
## Data preperation
```{r, fig.width=10, fig.height=4}
# Statistical info main effects
# Stats_Bb <- paste0("LMM: p = 0.779")
# Stats_Mp <- paste0("LMM: p = 0.015")
# Stats_MpN <- paste0("LMM: p = 0.322")
Stats_All <- paste0("GLMM: Aphid species p = 0.010; \nSoil p = 0.352; \nInteraction p = 0.604")

DataSum_All <- data.frame(Soil_conditioning = rep(c("CTRL", "Aphid"), times = 2),
                          Aphid_species = rep(c("Mp", "MpN"), each = 2),
                         Letters = c("a", "", "b", ""))

strip0 <- strip_themed(background_x = elem_list_rect(fill = c("#BBBBBB", "#A3BE8C", "#CC79A7"))
                        #text_x = elem_list_text(colour = c(rep("white", 5), rep("black", 7)))
                       )
```

## All aphid species
```{r, fig.width=4, fig.height=4}
ggplot(data = data,
       mapping = aes(y = Root_biomass, x = Soil_conditioning, fill = Soil_conditioning)) +
  stat_boxplot(aes(y = Root_biomass, x = Soil_conditioning), 
               geom = "errorbar",
               linetype = 1,
               width = 0.2) +
  geom_boxplot(outliers = FALSE) + #do not show outliers, this is shown by jitter
  facet_wrap2(~ Aphid_species,
             nrow = 1,
             strip = strip0,
             labeller = labeller(Aphid_species = c(Bb = "Bb", Mp = "gMp", MpN = "rMp"))) +
  geom_jitter(width = 0.25,
              height = 0,
              color = "black",
              alpha = 0.2) + # Transparency is regulated with the alpha argument
  stat_summary(fun = mean,
               geom = "point",
               size = 1.5,
               color = "gray30",
               fill = "white",
               shape = 23) + #Shows the mean as a white circle
  geom_segment(aes(x = 0.8, y = 0.38, xend = 2.2, yend = 0.38)) +
  geom_text(data = DataSum_All,
            aes(label = Letters, y = 0.4, x = Soil_conditioning), # fill out the significant letters
            size = 4,
            hjust = -2.5,
            #position = position_dodge(0.5)
           ) +
  # geom_text(data = DataSum,
  #           aes(label = lab2, y = 23.5), # fill out the significant letters
  #           size = 8,
  #           hjust = -1.1,
  #           #position = position_dodge(0.5)
  #          ) +
  scale_y_continuous(expand = c(0, 0),        #start graph at y = min and x = min
                     #breaks = seq(0, 25, 5), #steps on the y-axis
                     limits = c(0, 1.2*max(data$Root_biomass))) +   #y limits
  scale_fill_manual(values = c("#882255", "#009E73")) + # Manually change the colors of the bars. You need to define fill in second line of the plot script to get it working; c("#009E73", "#56B4E9")
  ylab("Root biomass (g)") +    #y-label with Mp in italic
  xlab("Soil treatment") +
  ggtitle(Stats_All) +
  theme(panel.background = element_rect(fill = "white"), #theme of the graph
        panel.border = element_blank(),
        axis.line = element_line(), #show line for x and y axis
        plot.title = element_text(size = 10, hjust = 0),
        axis.text = element_text(size = 13, color = "black"),
        axis.title = element_text(size = 16),
        axis.title.x = element_text(vjust = -0.5),
        axis.title.y = element_text(vjust = 2.5), #, hjust = -0
        strip.text = element_text(size = 13),
        plot.margin = margin(5.5, 12, 5.5, 5.5, "points"),
        legend.position = "none")

mapply(function(x)
  ggsave(plot = last_plot(),
         filename = x,
         path = "C:/Users/kreek001/OneDrive - Wageningen University & Research/Chapters/Experimental Chapter 1/R_Scripts/Final_figures",
         scale = 2.2,
         width = 3.8,
         height = 4,
         units = "cm",
         dpi = 300),
  x = c("FP_Aphid_Root_biomass_All.svg", "FP_Aphid_Root_biomass_All.png"))
```
